services:
  - type: web
    name: kindo-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.13
      - key: APP_NAME
        value: "Kindo School Payments API"
      - key: APP_VERSION
        value: "1.0.0"
      - key: LOG_LEVEL
        value: INFO
      - key: ENVIRONMENT
        value: production
      - key: CORS_ORIGINS
        value: '["https://kindo-8r9m.onrender.com"]'
      - key: DATABASE_PATH
        value: "app/data/kindo.db"
